<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

/**
 * {context} controller for the {module_name} module.
 *
 * Generated by Bonfire's Code Builder on {generate_date}.
 * Generated for {generate_user}.
 */
class {context_ucf} extends {extend} {

	//--------------------------------------------------------------------

	public function __construct()
	{
		parent::__construct();
	}

	//--------------------------------------------------------------------

	public function index()
	{

	}

	//--------------------------------------------------------------------

	public function create()
	{
		$this->auth->restrict();
	}

	//--------------------------------------------------------------------

	public function edit($id)
	{
		$this->auth->restrict();
	}

	//--------------------------------------------------------------------

	public function delete($id)
	{
		$this->auth->restrict();
	}

	//--------------------------------------------------------------------

	//--------------------------------------------------------------------
	// !Private Methods
	//--------------------------------------------------------------------

	/**
	 * Validates and saves the data.
	 *
	 * @param  string $type Operation type. Either 'insert' or 'update'
	 * @param  INT $id   The primary key of the record to update. Not needed
	 *                      for inserts.
	 *
	 * @access private
	 *
	 * @return bool
	 */
	private function save($type='insert', $id=null)
	{

	}

	//--------------------------------------------------------------------

}